### ISSUE TITLE
Traducción del workshop javascripting

### ISSUE THREAD

**Issue by a0viedo** [nodeschool/montevideo#3]
Acabo de terminar con los últimos arreglos al [repo](https://github.com/a0viedo/javascripting/tree/es) dónde tenemos la traducción del workshop que vamos a utilizar el Sábado. Perdón por el poco tiempo de aviso, estuvimos a las apuradas entre varios para finalizar todo. Cualquier error que encuentren me avisan por favor ( aunque ya le dí varias chequeadas por mi cuenta).

**Comment by tavofigse** [comment]
Creo que es npm install -g javascripting-es
