### ISSUE TITLE
Your logo is cool! Can you put it to the hexdex?

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/montevideo#5]
There is a collection of logos on the nodeschool page: http://nodeschool.io/hexdex.html can you add your logo here: https://github.com/nodeschool/nodeschool.github.io/blob/master/hexdex.html#L87 ?

**Comment by RodrigoEspinosa** [comment]
Hello @martinheidegger! Glad you like it, our designer @guillecura did a great work! 

I just fork the repo and will PR with the logo soon, thank you!

**Comment by martinheidegger** [comment]
:+1:
