### ISSUE TITLE
Contacto Coderhouse

### ISSUE THREAD

**Issue by eafelix** [nodeschool/montevideo#8]
Chicos, como estan? Mi nombre es Felix, yo ayude a @a0viedo con varios nodeschool aca en buenos aires. 
Surgio de parte de Coderhouse querer su contacto para dar soporte a la comunidad y eventos como nodeschool o meetups.

**Comment by pdjota** [comment]
Hola Felix, un gusto. De momento estamos enfocados en la JSConfUY https://jsconf.uy capaz que nos pueden dar una mano ahí y luego preparamos alguna actividad más específica de NodeSchools. ¿te parece si seguimos la conversación con hola@jsconf.uy ?

**Comment by eafelix** [comment]
Buenisimo, la copio a la manager de Coderhouse y conversamos alli. Gracias! nos vemos en el la jsConfUY, ya aca todos tenemos nuestras entradas :).
